version: '3.7'

networks:
  mynet:
  
services:
  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile.rabbit
    ports:
      - "15672:15672"  
      - "61613:61613"  # STOMP port
      - "15674:15674"  # STOMP over WebSockets port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - mynet

  mariadb:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    networks:
      - mynet

  # test:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.web
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - ENDPOINT=${ENDPOINT}
  #     - KEY=${KEY}
  #   volumes:
  #     - "uploads_volume:/uploads"
  #     - "processed_images_volume:/processed_images"
  #   container_name: test
  #   depends_on:
  #     - rabbitmq
  #     - mariadb

volumes:
  rabbitmq_data:
  uploads_volume:
  processed_images_volume:

